version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: myprojectpassword
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/

  redis:
    image: redis:latest

  celery:
    build:
      context: ./celery/
    depends_on:
      - redis
    volumes:
      - .:/app

  django:
    build:
      context: ./django/
    depends_on:
      - db
      - redis
      - celery
    volumes:
      - .:/app

volumes:
  postgresql_volume:{}